name: "Build"

on:
  workflow_dispatch:
  # build on push to master
  push:
    branches:
      - master

  # Do not build on internal pull requests
  # pull_request:

  # Do not allow to trigger for external PRs
  # workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: foldu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pathsToPush: result
      - run: |
          nix build .
